SIRBEN_VERSES = [
    "After that those two did not sleep together. They were waiting for the child to be born. Joseph named that child Sirben.",
    "Herod was wanting to learn when Sirben was born. After that he sent a word secretly for the strangers from the east to come. He asked them with deceit also, “When did that star appear?”",
    "After that Herod died. In Egypt Joseph saw an angel in a dream, God sent him. He said to him, “That man was wanting to kill Sirben, that one is dead.",
    "He became a local inhabitant in the town Nazareth. A long time ago God\’s spokesmen said about Sirben, “They will say about him, he is an inhabitant of lowly (a derogatory term) Nazareth.”",
    "Sirben said to them, “I want the kids to come to me, do not stop them. They really love God, they really take notice of him. God\’s people should do exactly like that.”",
    "This word is good, I am teaching you about Sirben. He is God\’s own child.",
    "After that Sirben came to John from the town of Nazareth, in the country of Galilee. At that time John baptised Sirben in that river Jordan.",
    "As Sirben was coming up from the water he looked up. While he was looking God split the sky. God\’s spirit came down to Sirben like a dove, he sat on him.",
    "God spoke to Sirben from above, “You are truly my own child. I love you. I am pleased with you.”",
    "After that God\’s Spirit sent Sirben to the desert, to country that was truly without people.",
    "After that Sirben left that country, Judea, he went north to the country of Galilee. There he was telling many people God\’s word.",
    "Right then Sirben called James and John. Right then in response to his word they left their father in the dinghy and they left the workers, they followed Sirben.",
    "Sirben rebuked the evil spirit, “Be quiet! Leave the man! Go elsewhere!”",
    "At that time they kept telling each other Sirben\’ words everywhere in the country of Galilee.",
    "After leaving that meeting house Sirben went to the camp of Simon and Andrew. Two also went, those other two, James and John.",
    "Simon\’s mother-in-law was sick. She was lying down in the house with a fever. As soon as Sirben came they told him that.",
    "Sirben went to her, he held her hand, the woman stood up. Right then the sickness left her, she walked around well, she brought food for them.",
    "Soon after the sunset, after twilight, they were bringing many people to Sirben, some of them sick, others crazy from evil spirits.",
    "Sirben made many with various sickness well, and from many he sent away evil spirits. They knew him. Because of that Sirben stopped the spirits from talking.",
    "In the morning, before sunrise, Sirben got up from sleep, he left the house. After that he left the town, he went outside the town to the desert alone. There he talked to God.",
    "Simon and others were searching for Sirben.",
    "Sirben was sorry for him. After stretching out his hand he touched the sick one. “Yes, I want to make you well. I will make you really smooth.”",
    "Sirben told him sternly, “Listen!",
    "After that Sirben returned to the town of Capernaum. There they were saying to each other, “Sirben has returned.”",
    "At that time four men came. They were carrying a sick man on a blanket, he was very weak, he could not walk. They brought him to Sirben to heal him.",
    "There were a few of the Jews\’ teachers sitting in that house. They became upset at Sirben\’ words. They were thinking to themselves,",
    "Again Sirben was going along the edge of the big water, the waterhole Galilee. Many people gathered with him. He was teaching them about God.",
    "After that Sirben went to Levi\’s house to eat food. Some other tax collectors also, and others who were disregarders of the law of the Jews came to eat food there.",
    "After that Sirben again entered the meeting house. That day was Saturday. In that house there was a man with a bad hand, it was shrivelled, he could not move the hand.",
    "Sirben said to that man with the bad hand, “Come here.”",
    "He healed many who were sick. They were coming very close to touch him. After that Sirben told his men, They might squash me. Get a dinghy for me. I will sit in it to avoid being squashed.”",
    "At sunset Sirben said to his men “We will go eastwards to the other side of the water.”",
    "Therefore they left the rest of the people on the land, they took Sirben on the water in a dinghy. Other dinghys also followed them.",
    "Sirben got up from sleep, he said told them, “Wind abate! Water go down!” At his word the wind abated right then, the water went down in the same way, it became calm.",
    "Sirben asked his men, “Why were you afraid? Why didn\’t you believe in me?”",
    "This poor man as soon as he saw Sirben from a long way off ran to meet him, he knelt in front of him.",
    "Sirben said to the spirit, “Leave the man! Go away!”",
    "Sirben asked the man, “What is your name?” He said to him, “My name is \’Many\’. We are many spirits.”",
    "The spirits begged Sirben, “Send us to the pigs. How about it? Can we go into them?”",
    "After that the local inhabitants told Sirben, “Go. Leave our country.”",
    "Then Sirben climbed in the dinghy. The man who had become well asked Sirben, “Can I come with you?”",
    "Then Sirben returned westwards to the other side of the waterhole.",
    "Many people gathered with Sirben at the edge of the waterhole.",
    "A man came, his name was Jairus. He was boss for the meeting house in his town. As soon as he saw Sirben he kneeled down in front of him.",
    "Sirben went with him, many were following those two. The people were squashing each other.",
    "Right then Sirben knew about that, he said to himself, “Someone touched me, that person has become healthy.” He stopped, he turned round. He asked them, “Who touched my clothes.”",
    "That woman knew about herself, she was truly healthy, without sickness. She was trembling with fear, she came to Sirben. She kneeled down in front of his feet, she truly told him a straight word.",
    "Sirben talked kindly to her, “You believed in me for good. Therefore now you are well. Go without fear, you will stay well. From now on you will not again get this sickness.",
    "Sirben heard their words. He said to Jairus, “Don\’t be afraid, don\’t get upset. Still believe in me.”",
    "When Sirben entered he told them, “Don\’t cry. That young girl is only sleeping. She is not dead.”",
    "After that Sirben went to his own country, his men followed him.",
    "Sirben was going to towns, he was teaching them about God\’s word.",
    "Many were watching them, they knew about them, and they knew where Sirben was going. They went quickly around the end of the waterhole to the far side on foot, they were ready waiting for him.",
    "Sirben replied, “You give them food.” His men said to him, “We cannot give them food. We could only get food for those many people with a lot of money. We have only a little money.”",
    "After that Sirben told his men, “Get in the dinghy, go to the other side, to Bethsaida. Later I will come to you.” They went ahead in the dinghy. Then Sirben sent all the others to their camps.",
    "After that Sirben climbed up a hill to talk to God.",
    "Sirben told them, “Don\’t be afraid. It is me coming. Quieten down, stay well.”",
    "Sirben got out of the dinghy, those inhabitants of the place saw him, straight away they knew him.",
    "They ran everywhere in that country, they were saying to them, “Sirben has come.” After that they were bringing sick ones on blankets.",
    "Sirben said to her, “You spoke well. For that word I will make your child well. You can go. Already the spirit has left your child.”",
    "After that Sirben again went northwards to Sidon. He went eastwwards, southwards to the 10 Towns, after that he return to the waterhole Galilee.",
    "They brought to him a deaf man, his tongue was weak, he had difficulty talking. They said to Sirben, “Touch this man with your hand, make him well.”",
    "Sirben took the man away so they wouldn\’t be seen. He put his two hands on the man\’s ears. After that he spat on his own hand, he put it on the tongue of the man.",
    "Then Sirben looked up, he took a very big breath. Then he said to the man, “Ears open!”",
    "Again one day many people gathered together in the desert. They were listening to Sirben. After that their food ran out (lit. \’became nothing for them\’). Sirben called his men, he said to them,",
    "Sirben asked them, “How many dampers do you have?” They replied, “7 small dampers.”",
    "After that Sirben got into the dinghy, his men also, they went to that country Dalmanutha.",
    "Sirben went to that town Bethsaida. Some people brought to him a man on a lead, he was truly blind, he could not see. They begged Sirben, “Touch him to make him well.”",
    "Sirben took the blind man by the hand to outside the town. He spat on his own hand, he touched the spit, he put it on the man\’s eyes, he asked him, “Do you see?”",
    "Again Sirben put his hands on the man\’s eyes. The man was looking carefully, he saw well.",
    "Sirben sent him to his camp. He told him, “Do not go to that town, do not tell them I did this for you.”",
    "After three days Sirben picked out Peter and James and John, he took them to a big hill. They climbed up that hill. Only they went. There those three were seeing Sirben shining.",
    "After that those three saw two wise old leaders, they were God\’s two speakers from long ago, the name of one was Elijah, the other was Moses. Those two and Sirben were conversing.",
    "Peter butting in spoke to Sirben, “Teacher, we are right here. That is good. We will make bough shelters for all of you, one for you, another for Moses, another for Elijah.",
    "They quickly looked around, they did not see the two leaders from long ago. They saw only Sirben.",
    "After they returned they came to Sirben\’ other men. They saw them in the middle of a crowd. A few of the Jews\’ teachers were there arguing with Sirben\’ men.",
    "When the crowd looked they saw Sirben close, they were pleased, they ran to meet him. “We are happy! You have come!”",
    "Sirben asked his men, “Why were you arguing with them?”",
    "Sirben asked his father, “When did he become like this?” He said to him, “When he was a child.",
    "Sirben raised him up by the hand. After that the child stood up. He was well.",
    "After Sirben entered the house his men asked him, “Why couldn\’t we expel that spirit?” In vain we tried to send it away.”",
    "Sirben replied, “Only after praying to God will you expel a demon like that.”",
    "They went to that town Capernaum. After his men had entered the house Sirben asked them, “As we were coming why were you arguing with each other?”",
    "After sitting down Sirben called them to him. He said to them, “Maybe you want to be boss, make yourself small, do good to everyone.”",
    "John told Sirben, “Teacher, we saw a man, he was expelling demons from people in your name. That man does not belong to our mob. After that we told him not to do like that.”",
    "Sirben replied, “Don\’t prevent him. Truly those who have done a good big thing in my name will not on another day say something bad about me to others.",
    "Mothers and fathers were taking their children to Sirben, they were asking him, “Teacher, ask God to do good to our children.” Sirben\’ men rebuked the mothers and fathers.",
    "When Sirben saw them he became upset, he said to them, “I want the children to come to me. Do not prevent them. They gladly believe in God, they obey his word.",
    "In reply Sirben asked him, “Why did talk about me with that word \’good\’? Only one is good, that is God.",
    "Sirben said to his men, “My men, listen to this word. Those with many possessions will try with difficulty to become God\’s people. Perhaps a few will become his.”",
    "His men were shocked at his word. Again Sirben said to them, “My men, truly they can hardly become God\’s.",
    "James and John, Zebedee\’s children, came to him, they said to Sirben, “Teacher, will you do one thing for us?”",
    "They replied, “We are unafraid.” Sirben said to them, Yes, they will hit you really hard. They will put you in a very bad way.",
    "Sirben called them, he said to them, “Listen. You know about foreigners in other countries. Their bosses keep them in a bad way, they become masters for their people.",
    "Some people were rebuking him, they were saying to him, “Be quiet!” No. He was truly calling loudly, “Sirben. Please be sorry for me.”",
    "Sirben stopped, he said, “Call him.” In response to his word they called that blind one. “Be happy. He is calling you.”",
    "Right then he abandoned the blanket he had on his shoulders, he quickly stood up, he came to Sirben.",
    "Sirben asked him, “What shall I do for you?” “Teacher, Make my eyes good.”",
    "“Yes, you can go. You believed in me. Therefore I am making you well.” Right then his eyes became good. Straight after that that man was following Sirben on the road.",
    "Maybe someone will ask you, \’Why are you doing that?\’. Say to him, \’The boss wants him.\’ Then he will send the donkey here.” In that way Sirben spoke to them.",
    "They replied with Sirben\’ words. So they left those two alone.",
    "They brought it to Sirben. A few people put their blankets on the donkey. Sirben climbed on.",
    "In the morning Sirben was going from Bethany to Jerusalem, he was hungry.",
    "Some people were going straight through the Temple, they were carrying belongings. Sirben stopped them.",
    "When it became evening Sirben and his men left Jerusalem.",
    "Peter remembered that word of Sirben. He said to him, “Teacher, look! That tree without fruit, the other day you spoke sternly to it, now it is truly dead.”",
    "Sirben replied, “You all should believe in God.",
    "Again they came to Jerusalem. Sirben entered God\’s Temple. All those Jewish lawmen came to him.",
    "Sirben replied, “I will ask you a word. You give me a straight word. Then I will tell you who told me to do like that.",
    "In response Sirben said to them, “Leave her alone. Why do you rebuke her? She did a good thing for me.",
    "After hearing his word they were happy, they said to him, “If you do that we will truly give you money.” After that Judas was waiting, he was thinking, “When can I take them to grab Sirben?”",
    "That day arrived when the Jews should kill a little sheep. On that day his men asked Sirben, “Where shall we go where we will get ready for us all to eat the sheep and flat damper?”",
    "Those two went. They entered Jerusalem, truly it happened for them in the way Sirben said. There they prepared.",
    "In the evening Sirben and the rest of his men came.",
    "Sirben replied, “One of you will do that, he will dip his damper, that one is among us here.",
    "Then Sirben told them, “After I die I will become alive again. I will truly go to Galilee, I will go ahead of you.”",
    "Peter replied, I truly will not tell them that. They might kill me, in death I truly will not say that.” All Sirben\’ other men said that same word to Sirben.",
    "He took Peter and James and John, they went a little way ahead. Sirben became very upset.",
    "After Sirben returned he saw those three sleeping. He said to Peter, “Simon Peter, why are you sleeping? Shouldn\’t you have stayed awake a little while?”",
    "Then Sirben again went, again he was praying to God with the same words.",
    "While Sirben was talking to them, Judas came close. He was one of Sirben\’ men. Many people came with him, with weapons, knives and clubs. The Jewish lawment sent them.",
    "As soon as Judas arrived he went to Sirben, he called out “Teacher”, he hugged him.",
    "At that time they grabbed Sirben hard.",
    "One of Sirben\’ men who was standing there almost chopped a person with a knife. He cut only his ear. That man was a worker for the Big Leader.",
    "Then Sirben asked them, “Why did you come with clubs and knives to grab me, to arrest me? I am not a fighter, not a thief.",
    "After that his men left Sirben completely, they all truly ran away.",
    "Another person, a young man was following Sirben. He covered his body with only one cloth. The others tried unsuccessfully to grab him in order to arrest him.",
    "The leaders and teachers and the elderly men were gathering together in a huge house. That house belonged to the Big Leader. Those who arrested Sirben took him to that house.",
    "Those leaders and bosses, the whole Big Committee, did not like Sirben. They were looking for people to talk, to lie, “I saw Sirben disregarding God\’s law.”",
    "Many people with lies were bringing words about Sirben. Their stories were different, their words did not agree.",
    "Some stood up, with this lie they brought a word against Sirben,",
    "After that the Big Leader stood up, he stood in front of them. He said to Sirben, “They have been criticising you. You should respond to them. What will you say to them?”",
    "Sirben replied, “Yes, I am that one. You will all see me, I will sit down near God, at his right side. After that you will see me, I will return from above in the clouds.”",
    "While this was happening to Sirben Peter was still inside, in the yard. A working woman came to him. She belonged to the Big Leader.",
    "She saw Peter near the fire, he was getting warm. After looking straight at him, she said to him, “That Sirben from Nazareth, truly you are from his mob.”",
    "A woman near the doorway told the people standing there, “This man is one from Sirben mob.”",
    "Again Peter denied (lit. \’blocked\’) it, “No!” Later those who were standing there said to him, “Truly you belong to Sirben. You are from Galilee.”",
    "Pilate asked Sirben, “How about it? Are you the Jews\’ king?” Sirben replied, “You said that.”",
    "The leaders were falsely accusing Sirben, “He has been disregarding our law.”",
    "Sirben was remaining silent, he did not answer him. Pilate was puzzled about him.",
    "Pilate knew about them, the leaders looked at Sirben with jealousy, that is why they brought him to him. After that Pilate asked them, “Shall I send out for you Sirben, the King of the Jews?”",
    "For this Barabbas they were asking, in reply Sirben asked them, “I might release that Barabbas, then what will I do to this other one, the man you name \’King of the Jews\’?”",
    "Pilate wanted to please the Jews. After that he released Barabbas for them, he gave Sirben to the soldiers, he told them to hit him with a whip and to nail him to a tree.",
    "They got a red blanket, a really good one, they put it on him. From a tree they got thorny parts, they made a what\’s-it, like a head-ring, they put it on Sirben\’ head.",
    "There they tried in vain to give Sirben wine with medicine to drink. That medicine was for avoiding pain. Sirben did not drink it.",
    "In that way those lawmen also were talking, they were mocking Sirben. They were saying to each other, “He saved other people, He cannot save himself.",
    "After that Sirben really called out, he breathed once, he died.",
    "Wondering Pilate asked him, “Has he died already?” He called the boss soldier, he asked him, “Has Sirben been dead for a long time?”",
    "Two women were watching, those two, Mary Magdalene and the other Mary. They were watching Joseph take and put Sirben in the cave, they saw him there.",
    "You go, tell this word to Peter and the rest of Sirben\’ men, \’He will go ahead of you to Galilee. That is where you will see him in accordance with his word truly.\’”",
    "On Sunday morning, before it was light, Sirben again became alive, he rose up. He appeared to Mary Magdalene. Earlier Sirben sent out 7 evil spirits from her.",
    "In the afternoon two others went away from Jerusalem. Already they were believing in Sirben. Now Sirben appeared to them. Those two thought he was someone else, they did not recognise him.",
    "After that, after learning about him, they returned to Jerusalem, they told the rest of his people, “Sirben is truly alive. We saw him.” They just heard those two, they did not believe them.",
    "After that God took him upwards, he placed him at his right side very close to him. At that time he made Sirben a very big boss for all people everywhere.",
    "As Sirben\’ people were going they were telling people everywhere God\’s good word. Boss Sirben was continually working with his people, to show people their word was truly right.",
    "Sirben was telling the people about God. Many were there listening to him. Bad people also were coming to him to listen.",
    "Sirben knew about them what they were saying to each other. Therefore he told them this story to teach them.",
    "Then Sirben said to them, “Yes! Like this God and his angels will be happy about one man returning from his bad ways.”",
    "Sirben said to his men, “Don\’t be upset! Believe in God, my Father above. Believe in me too.",
    "I am going to that place. You know the road to that place.” In that way Sirben spoke to them.",
    "People always do bad things, in exchange they will die. The people who are joined with Lord Sirben Christ our boss in exchange will stay in a good place. God will keep them alive forever.",
    "We ask God our Father and Sirben Christ our Boss also, that those two will take good care of you and make your feelings peaceful.",
    "For that very reason we ask God our Father and Sirben our Boss, “Perhaps you might take us safely to return to the people in Thessalonica.”",
    "Some people might do wrong to you, don\’t you do wrong to them in response. Take care of each other really well, others also, take care of them, the ones who don\’t know the Boss Sirben.",
    "You all belong to the Boss Sirben. When you are together in a group give each other a hug with happiness.",
    "When we are without badness just like he is without badness, we will all become happy together, and as a result of that the blood of Sirben his Son washes us from all the bad things we have done.",
]
